#!/bin/bash
# $Id: webv,v 1.88 2017/04/14 09:59:01 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/webv,v $
# $Revision: 1.88 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
syntax="$cmd: [-d] [-v] <id>|-V"
ver=`echo "$Id: webv,v 1.88 2017/04/14 09:59:01 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) debug=:;set -x;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $ver";exit;;
		 *) id=$1;shift;;
	esac
done
[ -z "$id" ]&&{ echo "syntax: $syntax" >&2;exit 1;}

config=${config:-"/usr/local/etc/webv.cf"}
[ -f "$config" ]||{ echo "$cmd: $config not found">&2;exit 1;}

eval `sed -ne "/^$id:/,/^$/{
	/^[ \t][^#]*/p
}" $config`

[ -z "$URI" ] &&{ echo "$cmd: No URI for $id in $config";exit 1;}

days=`expr \`date +%d\` - 1`
hour=`date +%H`
mins=`date +%M`
dhrs=`bc<<- .
	scale=2
	$hour + ($mins/60)
.`
# total hours elapsed in month
teh=`echo "scale=2;($days * 24 ) + $dhrs"|bc`

# total days in full month
td=`cal \`date +"%m %Y"\`|awk 'NF {DAYS=$NF} END {print (DAYS)}'`

# total hours in full month
tmh=`bc<<- .
	scale=2;$td * 24
.`
#[ $tmh -eq 0 ] && tmh=1

wget -qO - $URI|sed -ne '/Viewed traffic/s/[^0-9]*\([0-9,]*\).*/\1/p'|
	sed -e 's/,//'|
	if [ "$verbose" ];then
		#awk '{print "'$id'" "\t- Visitors so far:" $1 "\tAve:" $1/'$days' "\tPrediction:" $1/'$days'*'$td'}'
		awk -v id=$id '{
			printf "%7s %s %4i  %s %4.1f  %s %5.f\n",id,"- Visitors so far:",$1,"Ave:",$1/'$teh',"Prediction:",$1/'$teh'*'$tmh'}'
	else
		awk '{printf "%3i %4.1f %3.f\n",$1,$1/'$teh',$1/'$teh'*'$tmh'}'
	fi
